; Single Motor Flying Wing firmware
; 1 motor through ESC, 2 control servos, optional IMU/GPS.

[platformio]
default_envs = single_wing_esp32c3

[env:single_wing_esp32c3]
platform = espressif32@^6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

[env:single_wing_esp32]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:single_wing_f411]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200

[env:single_wing_f405]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
monitor_speed = 115200
